app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, PasswordField, SubmitField
from wtforms.validators import DataRequired


# 搜索表单页面
class SearchForm(FlaskForm):
    '''搜索表单页面'''
    # 搜索框
    search_input = StringField(
        label='搜索关键词',
        validators=[
            DataRequired("请输入要搜索的内容!")
        ],
        description="搜索",
        render_kw={
            "class": "search-input",
            "style": "width:50%;height: 50px;text-align: center;",
            "placeholder": "请输入您要搜索的内容..."
        }
    )
    # 提交
    submit = SubmitField(
        label='搜索',
        render_kw={
            "class": "search-btn",
            "style": "width:10%;height: 50px;",
            "value": "搜索"
        }
    )


# 注册表单页面
class RegisterForm(FlaskForm):
    '''用户注册表单'''
    # 账号
    username = StringField(
        label='用户名',  # 标签
        validators=[
            DataRequired("请输入账号！")
        ],
        description="用户名",
        render_kw={
            "id": "username",
            "class": "form-control",
            "placeholder": "请输入用户名",
            "maxlength": "20"
        }
    )

    # 密码
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired('请输入密码！')
        ],
        description="密码",
        render_kw={
            "id": "password",
            "class": "form-control",
            "placeholder": "请输入密码",
            "maxlength": "20"
        }
    )
    # 提交
    submit = SubmitField(
        label='注册',
        render_kw={
            "class": "form-control btn btn-primary",
            "id": "submit",
            "value": "立即注册"
        }
    )


# 登录表单页面
class LoginForm(FlaskForm):
    '''用户登录表单'''
    # 账号
    username = StringField(
        label='用户名',  # 标签
        validators=[
            DataRequired("请输入账号！")
        ],
        description="用户名",
        render_kw={
            "class": "form-control",
            "id": "inputEmail3",
            "placeholder": "username"
        }
    )

    # 密码
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired('请输入密码！')
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "id": "inputPassword3",
            "placeholder": "Password"
        }
    )
    # 提交
    submit = SubmitField(
        label='注册',
        render_kw={
            "class": "btn btn-default",
            "value": "登录"
        }
    )

app/home/__init__.py
# coding:utf8
from flask import Blueprint

home = Blueprint("home", __name__)
from app.home import views

app/home/views.py
# coding:utf8
from . import home  # 从当前目录导入home蓝图
from flask import render_template, request, flash, redirect, url_for, session
from app.home.forms import RegisterForm, LoginForm, SearchForm
from app import app
from app.models import User, Law, Case, Cases
from app import db, app
from flask_login import login_user, logout_user, login_required, current_user
from sqlalchemy import and_
import json
import os


# 首页
@home.route("/")
def index():
    return render_template('home/index.html')


# 搜索页
@home.route('/search/', methods=['GET', 'POST'])
@login_required
def search():
    data = request.args.get('search_key')
    words = ['%' + data + '%']
    rule = and_(*[Law.keywords.like(w) for w in words])
    res_1 = Law.query.filter(rule).first()
    if res_1:
        res_2 = Law.query.filter_by(id=res_1.similarity_1).first()
        res_3 = Law.query.filter_by(id=res_1.similarity_2).first()
        res = []
        res.append(res_1)
        res.append(res_2)
        res.append(res_3)
        return render_template('home/search.html', res=res)
    else:
        return redirect(url_for('home.index'))


# 条文详情页
@home.route('/provision/detail/<id>')
@login_required
def provision_detail(id):
    res_1 = Law.query.filter_by(id=id).first()
    if res_1:
        res_2 = Law.query.filter_by(id=res_1.similarity_1).first()
        res_3 = Law.query.filter_by(id=res_1.similarity_2).first()
        res = []
        res.append(res_1)
        res.append(res_2)
        res.append(res_3)
    return render_template('home/provision_detail.html', res=res)


mydata = ""

fname = os.getcwd() + "/app/templates/home/data.json"


# 文件上传页
@home.route('/upload')
@login_required
def upload():
    data = request.args.get('text')
    print(data)
    case = Case.query.filter_by(fact=data).first()
    js = {}
    js["criminals"] = case.criminals
    js["death_penalty"] = case.death_penalty
    js["imprisonment"] = case.imprisonment
    js["life_imprisonment"] = case.life_imprisonment
    js["punish_of_money"] = case.punish_of_money
    js["accusation"] = case.accusation
    js["relevant_articles"] = case.relevant_articles
    res = []
    res.append(js)
    a = {}
    a['site'] = res
    mydata = json.dumps(a, ensure_ascii=False).encode("utf8")
    with open(fname, 'wb') as f:
        f.write(mydata)
        f.close()
    return render_template('home/case_judge.html')


@home.route('/data/')
def data():
    return render_template('home/data.json')


# 案件描述页
@home.route('/case/desc/<id>')
@login_required
def case_desc(id):
    case = Cases.query.filter_by(id=id).first()
    return render_template('home/case_desc.html',case=case)


# 搜索明细
@home.route('/search/detail/<res>')
@login_required
def search_detail(res):
    res_1 = Law.query.filter_by(id=res).first()
    if res_1:
        res_2 = Law.query.filter_by(id=res_1.similarity_1).first()
        res_3 = Law.query.filter_by(id=res_1.similarity_2).first()
        res = []
        res.append(res_1)
        res.append(res_2)
        res.append(res_3)
    return render_template('home/search_detail.html', res=res)


# 法律条文
@home.route('/legalprovision/')
@login_required
def legalprovision():
    return render_template('home/legalprovision.html')


# 注册页
@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        # print(data)
        user = User.query.filter_by(username=data["username"]).first()
        if user:
            flash("用户名已经注册!", "err")
            return redirect(url_for('home.register'))
        user = User(
            username=data["username"],
            pwd=data["pwd"]
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功,请登录", "ok")
        return redirect(url_for('home.login'))
    return render_template('home/register.html', form=form)


# 登录页
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(username=data["username"]).first()
        if not user:
            flash("用户不存在！", "err1")
        elif data['pwd'] != user.pwd:
            flash("密码错误!", "err2")
        else:
            login_user(user)
            # 登录成功,保存会话
            session[user.username] = data['username']
            return redirect(url_for('home.index'))

    return render_template('home/login.html', form=form)


# 登出
@home.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash(u'您已退出登陆')
    return redirect(url_for('home.login'))


# 案件研判
@home.route('/case/judge', methods=['GET', 'POST'])
@login_required
def case_judge():
    return render_template('home/case_judge.html')


# 判决文书
@home.route('/judgmentdoc/')
@login_required
def judgmentdoc():
    return render_template('home/judgmentdoc.html')


# 文书明细
@home.route('/wenshu/detail/')
@login_required
def wenshu_search_detail():
    cases = Cases.query.limit(10)
    return render_template('home/wenshu_search_detail.html', cases=cases)

app/templates/home/grid.html
<style>
    .search-input {
        border-radius: 15px;
        outline: none;
    }

    .search-btn {
        color: rgb(255, 255, 255);
        background-color: rgb(50, 204, 255);
    }

    .search-a {
        display: inline-block;
        height: 30px;
        line-height: 30px;
        margin-right: 24px;
    }

    .select-a {
        display: inline-block;
        height: 20px;
        line-height: 20px;
        margin-left: 24px;
    }
</style>
<div class="row">
    <div class="col-md-1">LOGO</div>
    <div class="col-md-6">
        <div class="search">
            <form action="{{ url_for('home.search') }}" method="get">
                <input class="search-input" style="width:75%;height: 30px;text-align: center;" type="text"
                       placeholder="请输入您要搜索的内容..." name="search_key" required>
                <button class="search-btn" style="width:20%;height: 30px;" type="submit">搜索</button>
            </form>
        </div>
    </div>
    <div class="col-md-5">
        <a class="search-a" href="#">热搜</a>
        <a class="search-a" href="#">盗窃</a>
        <a class="search-a" href="#">知识产权</a>
        <a class="search-a" href="#">合同</a>
        <a class="search-a" href="#">离婚</a>
    </div>
</div>

<div class="row" style="margin-top:20px;">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        地域筛选
        <a class="select-a" href="#">不限</a>
        <a class="select-a" href="#">选择区域</a>
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        文书类别
        <a class="select-a" href="#">不限</a>
        <a class="select-a" href="#">刑事案件</a>
        <a class="select-a" href="#">民事案件</a>
        <a class="select-a" href="#">行政案件</a>
        <a class="select-a" href="#">赔偿案件</a>
        <a class="select-a" href="#">执行案件</a>
    </div>
</div>

app/templates/home/index.html
{% extends "home/nav.html" %}
{% block css %}
    <style>
        body {
            background: url('../../static/images/bg_index.jpg') no-repeat;
            -webkit-background-size:100%;
            background-size:100%;
        }
        .search-input {
            border-radius: 15px;
            outline:none;
        }

        .search-btn {
            color: rgb(255, 255, 255);
            background-color: rgb(50, 204, 255);
        }

        footer {
            position: fixed;
            bottom: 0px;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="search" style="margin:200px auto;">
        <form style="text-align: center;" action="{{ url_for('home.search') }}" method="get">
            <input class="search-input" style="width:50%;height: 50px;text-align: center;" type="text"
                   placeholder="请输入您要搜索的内容..." name="search_key" required>

            <button class="search-btn" style="width:10%;height: 50px;" type="submit">搜索</button>
        </form>
    </div>



    <div class="blank"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="knowledgePic" style="text-align: center;"></div>
        </div>
    </div>


{% endblock %}


app/templates/home/legalprovision.html
{% extends "home/nav.html" %}
{% block css %}
  <style>
    .search-input {
        border-radius: 15px;
        outline: none;
    }

    .search-btn {
        color: rgb(255, 255, 255);
        background-color: rgb(50, 204, 255);
    }

    .search-a {
        display: inline-block;
        height: 30px;
        line-height: 30px;
        margin-right: 24px;
    }

    .select-a {
        display: inline-block;
        height: 20px;
        line-height: 20px;
        margin-left: 24px;
    }
    #distance{
        margin-top:60px;
    }
</style>
{% endblock %}
{% block content %}

<link rel="stylesheet" type="text/css" href="../static/css/index2.css">
<div class="container">
	<div class="row">
    <div class="col-md-1">LOGO</div>
    <div class="col-md-6">
        <div class="search">
            <form action="{{ url_for('home.search') }}" method="get">
                <input class="search-input" style="width:75%;height: 30px;text-align: center;" type="text"
                       placeholder="请输入您要搜索的内容..." name="search_key" required>
                <button class="search-btn" style="width:20%;height: 30px;" type="submit">搜索</button>
            </form>
        </div>
    </div>
    <div class="col-md-5">
        <a class="search-a" href="#">热搜</a>
        <a class="search-a" href="#">盗窃</a>
        <a class="search-a" href="#">知识产权</a>
        <a class="search-a" href="#">合同</a>
        <a class="search-a" href="#">离婚</a>
    </div>
</div>

	<!-- 切换 -->
	<div class="row" id = "distance">
		<div class="col-md-4">
		  <ul class="nav nav-tabs nav-stacked" role="tablist">
		    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">所有</a></li>
		    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">行事案件</a></li>
		    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">民事案件</a></li>
		    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">赔偿案件</a></li>
		  </ul>
		</div>
		  <!-- 内容 -->
		<div class="col-md-8" style="border: 1px solid #000;">
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane active" id="home">
		    	<ul>
		    		<li>第一条　【立法目的】为了惩罚犯罪，保护人民，根据宪法，结合我国同犯罪作斗争的具体经验及实际情况，制定本法。</li>
		    		<li>第二条　【任务】中华人民共和国刑法的任务，是用刑罚同一切犯罪行为作斗争，以保卫国家安全，保卫人民民主专政的政权和社会主义制度，保护国有财产和劳动群众集体所有的财产，保护公民私人所有的财产，保护公民的人身权利、民主权利和其他权利，维护社会秩序、经济秩序，保障社会主义建设事业的顺利进行。</li>
		    		<li>第三条　【罪刑法定】法律明文规定为犯罪行为的，依照法律定罪处刑;法律没有明文规定为犯罪行为的，不得定罪处刑。</li>
		    		<li>第四条　【法律面前人人平等】对任何人犯罪，在适用法律上一律平等。不允许任何人有超越法律的特权。</li>
		    		<li>第四条　【法律面前人人平等】对任何人犯罪，在适用法律上一律平等。不允许任何人有超越法律的特权。</li>
		    	</ul>
		    </div>
		    <div role="tabpanel" class="tab-pane" id="profile">
		    	<ul>
		    		<li>第五条　【罪责刑相适应】刑罚的轻重，应当与犯罪分子所犯罪行和承担的刑事责任相适应。</li>
		    		<li>第六条　【属地管辖权】凡在中华人民共和国领域内犯罪的，除法律有特别规定的以外，都适用本法。</li>
		    		<li>第七条　【属人管辖权】中华人民共和国公民在中华人民共和国领域外犯本法规定之罪的，适用本法，但是按本法规定的最高刑为三年以下有期徒刑的，可以不予追究。
					中华人民共和国国家工作人员和军人在中华人民共和国领域外犯本法规定之罪的，适用本法。</li>
		    		<li>第八条　【保护管辖权】外国人在中华人民共和国领域外对中华人民共和国国家或者公民犯罪，而按本法规定的最低刑为三年以上有期徒刑的，可以适用本法，但是按照犯罪地的法律不受处罚的除外。</li>
		    	</ul>
		    </div>
		    <div role="tabpanel" class="tab-pane" id="messages">
		    	<ul>
		    		<li>第一条　【立法目的】为了惩罚犯罪，保护人民，根据宪法，结合我国同犯罪作斗争的具体经验及实际情况，制定本法。</li>
		    		<li>第二条　【任务】中华人民共和国刑法的任务，是用刑罚同一切犯罪行为作斗争，以保卫国家安全，保卫人民民主专政的政权和社会主义制度，保护国有财产和劳动群众集体所有的财产，保护公民私人所有的财产，保护公民的人身权利、民主权利和其他权利，维护社会秩序、经济秩序，保障社会主义建设事业的顺利进行。</li>
		    		<li>第三条　【罪刑法定】法律明文规定为犯罪行为的，依照法律定罪处刑;法律没有明文规定为犯罪行为的，不得定罪处刑。</li>
		    		<li>第四条　【法律面前人人平等】对任何人犯罪，在适用法律上一律平等。不允许任何人有超越法律的特权。</li>
		    	</ul>
		    </div>
		    <div role="tabpanel" class="tab-pane" id="settings">
		    	<ul>
		    		<li>第一条　【立法目的】为了惩罚犯罪，保护人民，根据宪法，结合我国同犯罪作斗争的具体经验及实际情况，制定本法。</li>
		    		<li>第二条　【任务】中华人民共和国刑法的任务，是用刑罚同一切犯罪行为作斗争，以保卫国家安全，保卫人民民主专政的政权和社会主义制度，保护国有财产和劳动群众集体所有的财产，保护公民私人所有的财产，保护公民的人身权利、民主权利和其他权利，维护社会秩序、经济秩序，保障社会主义建设事业的顺利进行。</li>
		    		<li>第三条　【罪刑法定】法律明文规定为犯罪行为的，依照法律定罪处刑;法律没有明文规定为犯罪行为的，不得定罪处刑。</li>
		    		<li>第四条　【法律面前人人平等】对任何人犯罪，在适用法律上一律平等。不允许任何人有超越法律的特权。</li>
		    	</ul>
		    </div>
		  </div>
		</div>
	</div>	

</div>

{% endblock %}

app/templates/home/nav.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>智能法判</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static',filename='images/logo.ico') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <link href="{{ url_for('static',filename='css/base.css') }}" rel="stylesheet">

    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% block css %}{% endblock %}
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
    <script>
        window.onload = function () {
            var oH2 = document.getElementsByTagName("h2")[0];
            var oUl = document.getElementsByTagName("ul")[0];
            oH2.onclick = function () {
                var style = oUl.style;
                style.display = style.display == "block" ? "none" : "block";
                oH2.className = style.display == "block" ? "open" : ""
            }
        }
    </script>
</head>
<body>
<header>
    <div class="tophead">
        <div class="logo"><a href="/">法律文书辅助平台</a></div>
        <div id="mnav">
            <h2><span class="navicon"></span></h2>
            <ul>
                <li><a href="{{ url_for('home.index') }}">首页</a></li>
                <li><a href="{{ url_for('home.legalprovision') }}">法律条文</a></li>
                <li><a href="{{ url_for('home.judgmentdoc') }}">判决文书</a></li>
                <li><a href="{{ url_for('home.case_judge') }}">案件判研</a></li>
                <li><a href="{{ url_for('home.login') }}">登录</a></li>
                <li><a href="{{ url_for('home.register') }}">注册</a></li>
            </ul>
        </div>
        <nav class="topnav" id="topnav">
            <ul>
                <li><a href="/">首页</a></li>
                <li><a href="{{ url_for('home.legalprovision') }}">法律条文</a></li>
                <li><a href="{{ url_for('home.judgmentdoc') }}">判决文书</a></li>
                <li><a href="{{ url_for('home.case_judge') }}">案件判研</a></li>
{#                <li><a href="{{ url_for('home.login') }}">登录</a></li>#}
{#                <li><a href="{{ url_for('home.register') }}">注册</a></li>#}
{#                <li><a href="#">{{ username }}</a></li>#}

                {% if current_user.is_authenticated %}
                    <li>欢迎<a href="#" style="color:blue;">{{ current_user.username }}</a>登录</li>
                    <li>
                        <a href="{{ url_for('home.logout') }}">
                            退出
                        </a>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('home.login') }}">登陆</a></li>
                    <li><a href="{{ url_for('home.register') }}">注册</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>
<div class="container">
    {% block content %}{% endblock %}
</div>

<footer style="margin-bottom:20px;background:none;">
<strong>版权 &copy; 2018-2019 归<a href="http://www.gzhu.edu.cn/">GuangZhou University</a>.</strong> 所有
</footer>
<div class="control-sidebar-bg"></div>
<script type="text/javascript" src="{{ url_for('static',filename='js/jquery-2.1.1.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/nav.js') }}"></script>

{% block js %}
{% endblock %}
</body>
</html>

app/templates/home/provision_detail.html
{% extends "home/nav.html" %}

{% block css %}
    <style>
        .search-input {
            border-radius: 15px;
            outline: none;
        }

        .search-btn {
            color: rgb(255, 255, 255);
            background-color: rgb(50, 204, 255);
        }

        .search-a {
            display: inline-block;
            height: 30px;
            line-height: 30px;
            margin-right: 24px;
        }

        .select-a {
            display: inline-block;
            height: 20px;
            line-height: 20px;
            margin-left: 24px;
        }

        .relative-law {
            color: #555;
            display: block;
            border: 1px solid #ddd;
            width: 88px;
            height: 42px;
            line-height: 42px;
            background: rgb(50, 204, 255);
            text-align: center;
            border-radius: 4px 4px 0 0;
            margin-bottom: 0px;
        }

        .nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover {
            background-color: rgb(50, 204, 255);
        }

        .key-words {
            color: #555;
            display: block;
            border: 1px solid #ddd;
            width: 60px;
            height: 35px;
            line-height: 35px;
            background: rgb(50, 204, 255);
            text-align: center;
            border-radius: 4px 4px 0 0;
            margin-bottom: 0px;
            margin-top: 25px;
        }

        .key-words-content {
            height: 80px;
            border: 1px solid #ddd;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-1">LOGO</div>
        <div class="col-md-6">
            <div class="search">
                <form action="{{ url_for('home.search') }}">
                    <input class="search-input" style="width:75%;height: 30px;text-align: center;" type="text"
                           placeholder="请输入您要搜索的内容...">
                    <button class="search-btn" style="width:20%;height: 30px;" type="submit">搜索</button>
                </form>
            </div>
        </div>
        <div class="col-md-5">
            <a class="search-a" href="#">热搜</a>
            <a class="search-a" href="#">盗窃</a>
            <a class="search-a" href="#">知识产权</a>
            <a class="search-a" href="#">合同</a>
            <a class="search-a" href="#">离婚</a>
        </div>
    </div>

    <div class="row" style="margin-top:20px;">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            地域筛选
            <a class="select-a" href="#">不限</a>
            <a class="select-a" href="#">选择区域</a>
        </div>
    </div>
    <div class="row" style="margin-top:20px;">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            文书类别
            <a class="select-a" href="#">不限</a>
            <a class="select-a" href="#">刑事案件</a>
            <a class="select-a" href="#">民事案件</a>
            <a class="select-a" href="#">行政案件</a>
            <a class="select-a" href="#">赔偿案件</a>
            <a class="select-a" href="#">执行案件</a>
        </div>
    </div>


    {#    法律条文，适用案件#}
    <div class="row" style="margin-top:30px;">
        <div class="col-md-8">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                              data-toggle="tab">法律条文</a></li>
                    {#                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"#}
                    {#                                               data-toggle="tab">适用案件</a>#}
                    {#                    </li>#}
                </ul>

                <!-- Tab panes -->
                <div class="tab-content" style="border:1px solid #ccc;">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <p>{{ res[0].catalog }}</p>
                        <p>内容：{{ res[0].content }}</p>
                        <p>执行日期：{{ res[0].date_execution }}</p>
                        <p>颁布单位：{{ res[0].enactment }}</p>
                        <p>颁布日期：{{ res[0].date_promulgation }}</p>
                        <p>时效性：{{ res[0].timeliness }}</p>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">
                        <ul class="list-group">
                            {% for i in res %}
                                <li class="list-group-item"><a
                                        href="{{ url_for('home.case_desc',id=i.id) }}">{{ i.catalog }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <p class="key-words">关键词</p>
            <div class="key-words-content">
                {{ res[0].keywords }}
            </div>
        </div>

        <div class="col-md-4">
            <p class="relative-law">相关法条</p>
            <ul class="list-group">
                {% for i in res %}
                    <li class="list-group-item"><a href="{{ url_for('home.provision_detail',id=i.id) }}">{{ i.catalog }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

app/templates/home/search_detail.html
{% extends "home/nav.html" %}

{% block css %}
    <style>
        .search-detail-classify {
            display: block;
            width: 80px;
            height: 35px;
            line-height: 35px;
            text-align: center;
            background: red;
            border: 1px solid #dddddd;
        }
    </style>
{% endblock %}
{% block content %}
    {% include "home/grid.html" %}

    <div class="row" style="margin-top: 40px;">
        <div class="col-md-12">
            <p class="search-detail-classify">法律条文</p>
            <ul class="list-group">
                {% for i in res %}
                <li class="list-group-item"><a href="{{ url_for('home.provision_detail',id=i.id) }}">{{ i.catalog }}</a></li>
                {% endfor %}
            </ul>
        </div>
{#        <div class="col-md-6">#}
{#            <p class="search-detail-classify">相关案件</p>#}
{#            <ul class="list-group">#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件1</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件2</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件3</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件4</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件5</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件6</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件7</a></li>#}
{#                <li class="list-group-item"><a href="{{ url_for('home.case_desc') }}">相关案件8</a></li>#}
{#            </ul>#}
{#        </div>#}
    </div>
{% endblock %}

app/templates/home/upload.html
{% extends "home/nav.html" %}
{% block css %}

{% endblock %}
{% block content %}
    {% include "home/grid.html" %}
    财富网官网
{% endblock %}

{% block js %}

{% endblock %}

app/templates/home/wenshu_search_detail.html
{% extends "home/nav.html" %}

{% block css %}
    <style>
        .search-detail-classify {
            display: block;
            width: 80px;
            height: 35px;
            line-height: 35px;
            text-align: center;
            background: red;
            border: 1px solid #dddddd;
        }
    </style>
{% endblock %}
{% block content %}
    {% include "home/grid.html" %}

    <div class="row" style="margin-top: 40px;">
        <div class="col-md-12">
            <p class="search-detail-classify">相关案件</p>
            <ul class="list-group">
                {% for i in cases %}
                <li class="list-group-item"><a href="{{ url_for('home.case_desc',id=i.id) }}">{{ i.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}